//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductPRoject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fittings
    {
        public int ID { get; set; }
        public int AccommodationID { get; set; }
        public int ProductID { get; set; }
        public int Accommodation { get; set; }
        public int Width { get; set; }
        public int Lenght { get; set; }
        public string Turn { get; set; }
        public int Quantity { get; set; }
    
        public virtual Accommodation Accommodation1 { get; set; }
        public virtual Product Product { get; set; }
    }
}
