//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductPRoject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardwareWarehouse
    {
        public int ID { get; set; }
        public int Сonsignment { get; set; }
        public int AccommodationID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Accommodation Accommodation { get; set; }
    }
}
