//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductPRoject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDbEntities : DbContext
    {
        public TestDbEntities()
            : base("name=TestDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accommodation> Accommodation { get; set; }
        public virtual DbSet<CustomItems> CustomItems { get; set; }
        public virtual DbSet<Fittings> Fittings { get; set; }
        public virtual DbSet<HardwareWarehouse> HardwareWarehouse { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductFabric> ProductFabric { get; set; }
        public virtual DbSet<ProductWarehouse> ProductWarehouse { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Textile> Textile { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
